spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/springboot_mybatis?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    #&allowPublicKeyRetrieval=true这一部分设置是mysql8里面的, 不设置验证会报错
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true

#  sql:
#    init:
#      schema-locations: classpath:sql/schema.sql
#      mode: always
server:
  port: 8089

logging:
  level:
    root: info  #日志等级
    com.example.mybatis_plus: info
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #下划线转驼峰
  global-config:
    db-config:
      logic-not-delete-value: 0  #逻辑删除
      logic-delete-field: 1
#  type-enums-package: com.example.mybatis_plus.enums.statusEnum




